import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ConnectKitButton } from 'ronin-connectkit';
import { useConnect } from 'wagmi';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { error } = useConnect()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>
          <ConnectKitButton />
          <br/>
      {error && <div>{error.message}</div>}
        </div>
      </main>
    </>
  )
}
